sudo: required
services:
  - docker

before_install:
  - docker build -t andie5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andie5/react-test npm test -- --coverage

after_success:
  - docker build -t andie5/multi-container-client ./client
  - docker build -t andie5/multi-container-nginx ./nginx
  - docker build -t andie5/multi-container-server ./server
  - docker build -t andie5/multi-container-worker ./worker
# Log into the docker cli
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push to docker hub
- docker push andie5/multi-container-client 
- docker push andie5/multi-container-nginx
- docker push andie5/multi-container-server
- docker push andie5/multi-container-worker
