sudo: required
services:
  - docker

before_install:
  - docker build -t dockeraa85/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockeraa85/react-test npm test -- --coverage

after_success:
  - docker build -t dockeraa85/multi-container-client ./client
  - docker build -t dockeraa85/multi-container-nginx ./nginx
  - docker build -t dockeraa85/multi-container-server ./server
  - docker build -t dockeraa85/multi-container-worker ./worker
  # Log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push dockeraa85/multi-container-client
  - docker push dockeraa85/multi-container-nginx
  - docker push dockeraa85/multi-container-server
  - docker push dockeraa85/multi-container-worker
